apiVersion: v1
kind: Service
metadata:
  labels:
    component: frontend
    app: todo
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: frontend
  selector:
    app: todo
    component: frontend
